### ISSUE TITLE
Add a way to find unused variables

### ISSUE THREAD

**Issue by ebrelsford** [stamen/mapbox-gl-style-build#12]
Currently there is no automated way to find unused variables, it would be handy to have one.

One way to go about this would be a command line tool that tracks all variables provided and reports back on which don't get used by any of the template styles.

This might be part of a more complete linting tool that would check for other issues such as variables used in templates that aren't defined.

**Comment by mulloverit** [comment]
**Success criteria**
Be able to run a script that names all of the variables not being used in a given stylesheet. Definition "unused varibles": we mean something defined in the build system but not used in the stylesheets.
