### ISSUE TITLE
How to use a variable within a different variable file? 

### ISSUE THREAD

**Issue by kateler** [stamen/mapbox-gl-style-build#26]
I would love to be able to use variables in my variable files, but I'm not sure how to do this. 

Here's a simple example.... suppose I'm building a "light" and a "dark" stylesheet. I might have `colorsLight.js` and `colorsDark.js` variable files, as well as another `colorsUniversal.js` variable file for colors that are the same in both light and dark. 

Then, I might want to include something like this in `colorsLight.js`: 

```
someFeature: [
	"match",
	["get", "someField"]
	"value1",
	"rgba(0, 0, 0, 1)",
	"value2",
	"rgba(255, 255, 255, 1)",
	context.colorsUniversal.transparent
]
```

In this particular case I could work around it, but it illustrates what I'd like to do in more complex situations. Is this possible already, and I just don't know the syntax? Or would it require code changes on your end? 

(Hello and yes, I'm using mapbox-gl-style-build at my current job! :wave: )

**Comment by aparlato** [comment]
Hi @kateler ! Sorry for the delayed response and glad to see this is getting use out in the world!

You should be able to do this with conventional JS rather than being a build system specific solution. So in your specific example of light, dark, and universal color variables files, that might look like:

```
// universal.js

module.exports = {
  red: 'rgb(255, 0, 0)',
};
```

```
// light.js

const universalColors = require('./universal');

module.exports = {
  varyingColor: [
    	"match",
	["get", "someField"]
	"value1",
	"rgb(255, 255, 255)",
         universalColors.red
  ]
};
```

```
// light.js

const universalColors = require('./universal');

module.exports = {
  varyingColor: [
    	"match",
	["get", "someField"]
	"value1",
	"rgb(0, 0, 0)",
	universalColors.red
  ]
};
```
Let me know if this solves this for you!

**Comment by kateler** [comment]
Thanks @aparlato ! That did work, and unlocked some more efficiency for us. 🚀

**Comment by aparlato** [comment]
Great to hear! Closing this as resolved then!
