### ISSUE TITLE
Two folders named "variants" is confusing

### ISSUE THREAD

**Issue by almccon** [stamen/mapbox-gl-style-build#29]
There's a folder called `templates/variants/` which contains the `.js` files that define each variant that the build system will generate, but we also have the top-level output folder which is also called `variants/` which contains the results from the build process.

Should we rename one or the other of these to be less confusing?

**Comment by aparlato** [comment]
@almccon this is actually customizable with an `--out-dir` flag. In most repos we've set up that up to be `variants` with the logic that matching the names provides clarity:

```
$(yarn bin)/mapbox-gl-style-build \
    --style-dir=templates/variants \
    --layer-dir=templates/layers \
    --out-dir=variants
```

Let's open an issue in the specific repos where we want to update this and we can update the appropriate line of the script and adjust any related Github actions that rely on that naming convention.
