### ISSUE TITLE
Support variable modifiers

### ISSUE THREAD

**Issue by kelsey-taylor** [stamen/mapbox-gl-style-build#5]
## Describe the issue

The build system currently allows you to set up variables that can be used across variants. It would be helpful to support math modifiers for these variables to avoid duplicating work. 

For example, I have a variable file with text size expressions for one set of variants. For another set of variants, I want the text to be larger overall, but adjustable for each variable (some *1.5 and some *2, for example) without needing to rewrite the original expression completely.

**Comment by aparlato** [comment]
Closed by https://github.com/stamen/mapbox-gl-style-build/pull/6!
